# Generated by Django 4.1.7 on 2023-04-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_last_login_supervisor_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='preference_list',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
