# Generated by Django 4.1.7 on 2023-04-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_preference_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='preference_list',
        ),
    ]
