# Generated by Django 4.2.4 on 2023-08-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_student_preference_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='capacity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
