# Generated by Django 3.2 on 2023-08-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_supervisor_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionMaker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
