# Generated by Django 3.2 on 2023-09-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_supervisor_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='capacity',
            field=models.CharField(max_length=100),
        ),
    ]
