# Generated by Django 4.1.7 on 2023-04-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor_name',
            field=models.CharField(default='default_supervisor', max_length=100),
        ),
    ]
