# Generated by Django 4.1.7 on 2023-04-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_project_project_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='supervisor_id',
            new_name='supervisor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supervisor_name',
        ),
    ]
