# Generated by Django 4.1.7 on 2023-04-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_preference_list'),
        ('main', '0004_projectlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supervisor'),
        ),
    ]
