# Generated by Django 4.2.4 on 2023-08-16 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_projectlist_student_alter_project_supervisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlist',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='projectlist',
            name='projects',
        ),
        migrations.AddField(
            model_name='projectlist',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectlist',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
            preserve_default=False,
        ),
    ]
